# ABOUTME: Exposes stable boundary contracts without eagerly importing unrelated contract modules.
# ABOUTME: Resolves convenience exports on first access so submodule imports retain narrow dependencies.

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS_BY_MODULE: dict[str, tuple[str, ...]] = {
    "aec_bench.contracts.evaluation_plane": (
        "AcceptanceManifestCommitment",
        "AcceptanceManifestReveal",
        "AcceptanceManifestRevealRule",
        "CriticFeedbackVisibility",
        "CriticRef",
        "CriticReleaseAuthorityRef",
        "CriticRole",
        "CriticSpec",
        "EvaluationBudgetPartition",
        "EvaluationBudgetPlan",
        "CandidateManifestScope",
        "EvaluationPlan",
        "EvaluationPlanAuthorityScope",
        "EvaluationPlanRef",
        "TaskVerifierFileInventoryEntry",
        "TaskVerifierSurface",
        "TaskVerifierSurfaceScope",
        "assert_acceptance_compatible",
    ),
    "aec_bench.contracts.execution_program": (
        "ActionNode",
        "BranchCondition",
        "BranchNode",
        "BranchOperator",
        "CompiledExecutionProgram",
        "ExecutionProgram",
        "ExecutionProgramRef",
        "FanoutNode",
        "JoinNode",
        "JoinStrategy",
        "LiteralValue",
        "OutputValue",
        "ProgramArgument",
        "ProgramLimits",
        "ProgramNode",
        "ProgramNodeKind",
        "ProgramOutputRef",
        "RecursionPolicy",
        "RetryPolicy",
        "StopNode",
        "StopOutcome",
        "VerifyNode",
    ),
    "aec_bench.contracts.evaluation_generation": (
        "CandidateAssignmentRef",
        "CandidateBatchRejectionClosure",
        "CandidateKindRequirement",
        "CandidateScheduleRef",
        "EvaluationBatchPlan",
        "EvaluationCohortBinding",
        "EvaluationCohortManifest",
        "EvaluationCohortPurpose",
        "EvaluationCohortRetirement",
        "EvaluationCohortTask",
        "EvaluationExecutionProfileRef",
        "EvaluationCriticRetirementRef",
        "EvaluationGenerationBudget",
        "EvaluationGenerationClosure",
        "EvaluationGenerationEvidenceRef",
        "EvaluationGenerationEvidenceRole",
        "EvaluationGenerationRetirementClosure",
        "EvaluationGenerationSourceRef",
        "EvaluationGenerationSpec",
        "EvaluationTaskIdentity",
        "GovernedBatchAssignmentEvidence",
        "PreparedEvaluationGeneration",
        "PreparedProposalTask",
        "GovernedBatchExecutionClosure",
        "GovernedBatchTerminalEvidence",
        "ProposalGenerationClosure",
        "ProposalGenerationPolicy",
        "TaskCandidatePlan",
    ),
    "aec_bench.contracts.adaptation": (
        "AdaptationCandidate",
        "AdaptationSpec",
        "DerivationStep",
        "expand_adaptation_spec",
        "VariationAxis",
    ),
    "aec_bench.contracts.trial_record": (
        "AdaptationProvenance",
        "AgentReference",
        "Completeness",
        "CostRecord",
        "DerivationStepRecord",
        "EnvironmentSnapshot",
        "FileReference",
        "InputRecord",
        "MetaHarnessTrialProvenance",
        "OutputRecord",
        "ProposalSessionTrialProvenance",
        "TaskReference",
        "TimingRecord",
        "TrialRecord",
        "WorldExecutionRecord",
        "WorldTrialProvenance",
    ),
    "aec_bench.contracts.advisor": (
        "AdvisorConfig",
        "AdvisorContextStrategy",
        "AdvisorRequest",
        "AdvisorResponse",
        "AdvisorUsageStats",
    ),
    "aec_bench.contracts.harness_instance": (
        "AgentBindingConfig",
        "CompiledHarnessBinding",
        "CompiledHarnessInstance",
        "ComputeBindingConfig",
        "ContextBindingConfig",
        "ContextSelectionStrategy",
        "HarnessBudget",
        "HarnessBindingConfiguration",
        "HarnessBindingKind",
        "HarnessBindingSpec",
        "HarnessCompileRequest",
        "HarnessContractEnforcement",
        "HarnessContractKind",
        "HarnessContractSpec",
        "HarnessInstanceRef",
        "HarnessRecursionPolicy",
        "HarnessRecipe",
        "HarnessTopologyRole",
        "ProgramOperationRef",
        "ProgramOperationSpec",
        "ProgramSurface",
        "ResultImportBindingConfig",
        "TaskSourceBindingConfig",
        "ToolAccessMode",
        "ToolBindingConfig",
        "VerificationBindingConfig",
        "VerificationPlacement",
        "VerificationStage",
    ),
    "aec_bench.contracts.experiment_manifest": (
        "AgentConfig",
        "ClientConfig",
        "ComputeConfig",
        "ExperimentManifest",
        "TaskSelector",
    ),
    "aec_bench.contracts.rubric": (
        "CATEGORY_WEIGHTS",
        "DimensionScore",
        "Rubric",
        "RubricCriterion",
        "RubricDimension",
        "RubricResult",
    ),
    "aec_bench.contracts.agent_output": (
        "AgentOutput",
        "AgentOutputStatus",
    ),
    "aec_bench.contracts.task_world": (
        "AgenticReviewProfile",
        "ClosureGate",
        "ConstructionGate",
        "ContainmentGate",
        "EventTrigger",
        "LogicProfile",
        "MaterializedTaskWorldRun",
        "OperationProfile",
        "TaskWorldProfile",
    ),
    "aec_bench.contracts.evaluation_result": (
        "Annotation",
        "ConfidenceMetadata",
        "ErrorSource",
        "ErrorTag",
        "EvaluationResult",
        "Judgment",
        "StewardshipEvaluation",
        "StewardshipEvaluationEvidence",
        "StewardshipIntegrityGates",
        "StewardshipMetricVector",
        "StewardshipTerminalLiability",
        "ValidityCheck",
    ),
    "aec_bench.contracts.authority": (
        "AuthorityAction",
        "AuthorityDecision",
        "AuthorityEvent",
        "AuthorityPrincipal",
        "AuthorityPrincipalKind",
        "BasisKind",
        "BasisReference",
        "HumanAuthorityApproval",
        "MotifPromotionAssurance",
        "OperatorAuthority",
        "OperatorCapability",
        "OperatorRole",
        "OriginStamp",
        "PromotionMonitorAttestation",
        "MotifPromotionQualification",
        "PromotionSubjectLineage",
        "TaintLabel",
        "derive_origin_stamp",
        "operator_authority_for",
    ),
    "aec_bench.contracts.repl": (
        "CalcTool",
        "DependencyTreeSchema",
        "FlatSchema",
        "JsonReplMixin",
        "OutputField",
        "ParameterField",
        "ParameterTable",
        "ReplSerializable",
        "SchemaSection",
        "SectionedSchema",
        "StandardsRef",
        "TaskInstruction",
        "TreeSection",
    ),
    "aec_bench.contracts.program_proposal": (
        "CandidateEvidenceKind",
        "CandidateGenerationCoordinate",
        "CandidateGenerationManifest",
        "DecompositionLeakageAudit",
        "DecompositionOptimizationCycle",
        "DecompositionProblemView",
        "EvaluationProposalFreeze",
        "FixedHarnessCapabilityProjection",
        "MatchedCandidateEvidenceRef",
        "MatchedEvaluationCoordinate",
        "OptimizationDisposition",
        "OptimizationSplit",
        "PairedCandidateComparison",
        "ProgramCandidateKind",
        "ProgramCandidateRef",
        "ProgramCandidateStudy",
        "ProposalFreeze",
        "PublicAuthorityBoundary",
        "PublicDataGapBoundary",
        "PublicSourceRef",
    ),
    "aec_bench.contracts.proposal_execution": (
        "CandidateBudgetPlan",
        "CompiledNodeContextScope",
        "FinalSynthesisSpec",
        "NodeBudgetReservation",
        "NodeEvidenceContract",
        "NodeInstructionVisibility",
        "MonolithicIncumbentProgram",
        "ProposalCandidateFailureCode",
        "ProposalCompilationRecord",
        "ProposalCompilationRejection",
        "ProposalCompilationStatus",
        "ProposalCompilationSuccess",
        "ProposalCompileDiagnostic",
        "ProposalCompileRejectionCode",
        "ProposalContainerTransitionRef",
        "ProposalContractCheckResultRef",
        "ProposalContractCheckStatus",
        "ProposalDiagnosticVisibility",
        "ProposalExecutionSemantics",
        "ProposalHandoffArtifactRef",
        "ProposalHandoff",
        "ProposalInputPort",
        "ProposalNodeExecutionResultRef",
        "ProposalNodeReceipt",
        "ProposalNodeReceiptStatus",
        "ProposalNodeSkipCause",
        "ProposalOutputPort",
        "ProposalPortKind",
        "ProposalSessionExecutionRef",
        "ProposalSessionPlan",
        "ProposalSessionReceipt",
        "ProposalSessionStatus",
        "ProposalSourceScope",
        "ProposalSourceScopeManifest",
        "ProposedDecompositionGraph",
        "ScopedSourceMaterialization",
        "SemanticSubtaskSpec",
    ),
    "aec_bench.contracts.constitution": (
        "ConstitutionalPrinciple",
        "ConstitutionManifest",
        "EarnedAutonomyParams",
        "InformationMinimalityParams",
        "ProgressObligationParams",
        "StatePersistenceParams",
        "SourceFidelityParams",
    ),
    "aec_bench.contracts.harness_kernel": (
        "ContentAddressedModel",
        "FrozenStrictModel",
        "KernelCapabilityKind",
        "KernelCapabilityRef",
        "KernelCapabilitySpec",
        "KernelManifest",
        "KernelPortCardinality",
        "KernelPortSpec",
        "KernelRef",
        "canonical_content_sha256",
        "validate_sha256",
    ),
    "aec_bench.contracts.evaluation_outcome": (
        "CandidatePlaneCost",
        "CommonModeBasis",
        "CommonModeBasisKind",
        "CriticEvaluationOutcome",
        "CriticGapDecomposition",
        "CriticPlaneCost",
        "EvaluationCostBreakdown",
        "EvaluationDisposition",
        "EvaluationOutcome",
        "IntegrityCheck",
        "IntegrityEvaluation",
        "ResourceCost",
        "SelectionNullEstimate",
        "ValidityEvaluation",
        "UtilityEvaluation",
    ),
    "aec_bench.contracts.dataset": (
        "DatasetDescription",
        "DatasetManifest",
        "DatasetSource",
        "DatasetTaskEntry",
    ),
    "aec_bench.contracts.evolution": (
        "DisciplineScore",
        "EvolutionConfig",
        "EvolutionCycleRecord",
        "EvolutionObservation",
        "EvolutionResult",
        "EvolvableLayer",
        "EvolverModelConfig",
        "FieldScore",
        "GateDecision",
        "MutationSummary",
        "ObservationEnrichment",
        "SkillEntry",
        "StagnationInfo",
        "StepResult",
        "TraceDigest",
        "TraceQueryRequest",
        "TraceSlice",
        "TraceSliceTurn",
        "WorkspaceManifest",
        "WorkspaceReadRequest",
        "WorkspaceSnapshot",
        "WorkspaceVersion",
        "WorkspaceWriteRequest",
    ),
    "aec_bench.contracts.task_definition": (
        "Difficulty",
        "EnvironmentSpec",
        "Lifecycle",
        "TaskDefinition",
        "ToolSpec",
        "VerifierSpec",
        "Visibility",
    ),
    "aec_bench.contracts.pricing": (
        "estimate_cost_usd",
        "match_pricing",
        "PRICING_PER_MTOK",
    ),
    "aec_bench.contracts.output_completion": (
        "evaluate_output_completion",
        "OUTPUT_COMMIT_ATTESTATION_SCHEMA_VERSION",
        "OUTPUT_COMPLETION_CONTRACT_SCHEMA_VERSION",
        "OutputCommitAttestation",
        "OutputCompletionContract",
        "OutputCompletionEvaluation",
        "OutputCompletionReason",
    ),
    "aec_bench.contracts.run_bundle": (
        "HarborRunPayload",
        "RunBundle",
        "RunTarget",
        "TaskSnapshotRef",
        "WorldSnapshotRef",
    ),
    "aec_bench.contracts.world_session": (
        "StewardshipStateSnapshotRef",
        "WORLD_SESSION_SCHEMA_VERSION",
        "WorldSessionExecutionKind",
        "WorldSessionOpenMode",
        "WorldSessionRequest",
        "WorldSessionResult",
    ),
    "aec_bench.contracts.continual_world": (
        "CONTINUAL_WORLD_DEFINITION_SCHEMA_VERSION",
        "CONTINUAL_WORLD_PROFILE_SCHEMA_VERSION",
        "ContinualWorldDefinitionRef",
        "ContinualWorldDefinitionSpec",
        "ContinualWorldProfileRef",
    ),
    "aec_bench.contracts.world_interface": (
        "WORLD_ACTOR_INTERFACE_SCHEMA_VERSION",
        "WORLD_CONTROL_INTERFACE_SCHEMA_VERSION",
        "WorldActorActionCapability",
        "WorldActorActionRequest",
        "WorldActorActionResult",
        "WorldActorBinding",
        "WorldActorCapabilityCatalogue",
        "WorldActorObservation",
        "WorldInterfaceError",
        "WorldControlCapabilityCatalogue",
        "WorldControlOperationCapability",
        "WorldControlProgress",
        "WorldControlReceipt",
        "WorldControlRequest",
        "WorldControlResult",
        "WorldControlVerification",
    ),
    "aec_bench.contracts.validators": (
        "LenientModel",
        "NonEmptyStr",
        "StrictModel",
    ),
    "aec_bench.contracts.library_catalogue": ("LibraryCatalogue",),
    "aec_bench.contracts.trajectory": ("MetaHarnessTrajectoryContext",),
    "aec_bench.contracts.synthesis": (
        "SynthesisCandidate",
        "SynthesisConfig",
        "SynthesisCriteria",
        "SynthesisInput",
        "SynthesisOutput",
    ),
    "aec_bench.contracts.jsonl": (
        "read_jsonl",
        "write_jsonl",
    ),
}

_EXPORT_MODULE_BY_NAME = {name: module_name for module_name, names in _EXPORTS_BY_MODULE.items() for name in names}
__all__ = tuple(_EXPORT_MODULE_BY_NAME)


def __getattr__(name: str) -> Any:
    """Load one stable convenience export without importing unrelated contracts."""

    module_name = _EXPORT_MODULE_BY_NAME.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return ordinary module names plus the lazily exported contract names."""

    return sorted({*globals(), *__all__})
