# ABOUTME: Builds, checks, and compares the generated world and lifecycle catalogues.
# ABOUTME: Keeps owner composition explicit and makes semantic catalogue content available to the CLI.

from __future__ import annotations

import inspect
import json
import tempfile
from collections.abc import Iterable, Mapping
from importlib import import_module
from pathlib import Path
from typing import Any, cast

from aec_bench.lifecycles.runtime.definition import LifecycleDefinition, LifecycleOwnerDescriptor
from aec_bench.worlds.runtime.definition import InteractiveWorldDefinition, InteractiveWorldOwnerDescriptor

type OwnerImport = tuple[str, str, str, str]

WORLD_OWNER_IMPORTS: tuple[OwnerImport, ...] = (
    (
        "dam-seepage-monitoring",
        "aec_bench.worlds.monitoring.dam_seepage",
        "WORLD_DESCRIPTOR",
        "DAM_SEEPAGE_DESCRIPTOR",
    ),
    (
        "wastewater-pump-station-stewardship.v1",
        "aec_bench.worlds.stewardship.wastewater_pump_station",
        "WORLD_DESCRIPTOR",
        "PUMP_STATION_DESCRIPTOR",
    ),
)

LIFECYCLE_OWNER_IMPORTS: tuple[OwnerImport, ...] = (
    (
        "drainage-model-evidence-lifecycle-review",
        "aec_bench.lifecycles.stormwater_design.drainage_model",
        "LIFECYCLE_DESCRIPTOR",
        "DRAINAGE_MODEL_DESCRIPTOR",
    ),
    (
        "facade-submittal-review-lifecycle",
        "aec_bench.lifecycles.structural_review.facade_submittal",
        "LIFECYCLE_DESCRIPTOR",
        "FACADE_SUBMITTAL_DESCRIPTOR",
    ),
    (
        "hydraulic-design-response-lifecycle-review",
        "aec_bench.lifecycles.stormwater_design.design_response",
        "LIFECYCLE_DESCRIPTOR",
        "DESIGN_RESPONSE_DESCRIPTOR",
    ),
    (
        "hydraulic-interaction-lifecycle-review",
        "aec_bench.lifecycles.stormwater_design.hydraulic_review",
        "LIFECYCLE_DESCRIPTOR",
        "HYDRAULIC_REVIEW_DESCRIPTOR",
    ),
)

_REPO_ROOT = Path(__file__).resolve().parents[2]

_WORLD_HEADER = """# Generated by scripts/generate_world_catalogue.py. Do not edit by hand.
# ABOUTME: Loads the checked-in composition generated from concrete world owners.
# ABOUTME: Keeps runtime discovery explicit, readable, and stable without a mutable registry.

from __future__ import annotations

"""

_LIFECYCLE_HEADER = """# Generated by scripts/generate_lifecycle_catalogue.py. Do not edit by hand.
# ABOUTME: Loads the checked-in lifecycle composition generated from concrete owners.
# ABOUTME: Keeps template discovery explicit, readable, and stable without a mutable registry.

from __future__ import annotations

"""


class CatalogueError(ValueError):
    """Base error for invalid catalogue inputs or generated output."""


class CatalogueValidationError(CatalogueError):
    """Raised when one or more catalogue rules fail."""

    def __init__(self, errors: Iterable[str]) -> None:
        self.errors = tuple(errors)
        super().__init__("; ".join(self.errors))


def _ordered_import_lines(owner_imports: tuple[OwnerImport, ...], runtime_import: str) -> str:
    ordered = tuple(sorted(owner_imports, key=lambda owner: owner[0]))
    return "\n".join(
        sorted(
            [f"from {module} import {attribute} as {alias}" for _, module, attribute, alias in ordered]
            + [runtime_import]
        )
    )


def render_world_catalogue(owner_imports: tuple[OwnerImport, ...] = WORLD_OWNER_IMPORTS) -> str:
    """Render the generated world composition from an explicit owner list."""

    ordered = tuple(sorted(owner_imports, key=lambda owner: owner[0]))
    imports = _ordered_import_lines(
        owner_imports,
        "from aec_bench.worlds.runtime.definition import InteractiveWorldDefinition, InteractiveWorldOwnerDescriptor",
    )
    descriptors = ",\n".join(f"    {alias}" for _, _, _, alias in ordered)
    return (
        f"{_WORLD_HEADER}{imports}\n\n"
        "# This tuple is generated by scripts/generate_world_catalogue.py. Keep entries sorted by task_world_id.\n"
        "WORLD_DESCRIPTORS: tuple[InteractiveWorldOwnerDescriptor, ...] = (\n"
        f"{descriptors},\n"
        ")\n\n\n"
        "def load_world_definitions() -> tuple[InteractiveWorldDefinition, ...]:\n"
        '    """Load the current definitions in the generated stable order."""\n\n'
        "    return tuple(descriptor.load() for descriptor in WORLD_DESCRIPTORS)\n\n\n"
        '__all__ = ("WORLD_DESCRIPTORS", "load_world_definitions")\n'
    )


def render_lifecycle_catalogue(owner_imports: tuple[OwnerImport, ...] = LIFECYCLE_OWNER_IMPORTS) -> str:
    """Render the generated lifecycle composition from an explicit owner list."""

    ordered = tuple(sorted(owner_imports, key=lambda owner: owner[0]))
    imports = _ordered_import_lines(
        owner_imports,
        "from aec_bench.lifecycles.runtime.definition import LifecycleDefinition, LifecycleOwnerDescriptor",
    )
    descriptors = ",\n".join(f"    {alias}" for _, _, _, alias in ordered)
    return (
        f"{_LIFECYCLE_HEADER}{imports}\n\n"
        "# This tuple is generated by scripts/generate_lifecycle_catalogue.py. Keep entries sorted by template_id.\n"
        "LIFECYCLE_DESCRIPTORS: tuple[LifecycleOwnerDescriptor, ...] = (\n"
        f"{descriptors},\n"
        ")\n\n\n"
        "def load_lifecycle_definitions() -> tuple[LifecycleDefinition, ...]:\n"
        '    """Load the current lifecycle definitions in generated stable order."""\n\n'
        "    definitions = tuple(descriptor.load() for descriptor in LIFECYCLE_DESCRIPTORS)\n"
        "    template_ids = tuple(definition.metadata.template_id for definition in definitions)\n"
        "    if len(template_ids) != len(set(template_ids)):\n"
        '        raise ValueError("generated lifecycle catalogue template IDs must be unique")\n'
        "    return tuple(sorted(definitions, key=lambda definition: definition.metadata.template_id))\n\n\n"
        '__all__ = ("LIFECYCLE_DESCRIPTORS", "load_lifecycle_definitions")\n'
    )


def catalogue_paths(root: Path = _REPO_ROOT) -> tuple[Path, Path]:
    """Return the committed generated catalogue paths below *root*."""

    return (
        root / "src" / "aec_bench" / "worlds" / "generated_catalogue.py",
        root / "src" / "aec_bench" / "lifecycles" / "generated_catalogue.py",
    )


def _source_descriptors() -> tuple[
    tuple[InteractiveWorldOwnerDescriptor, ...],
    tuple[LifecycleOwnerDescriptor, ...],
]:
    """Load descriptors only from the maintained explicit owner lists."""

    world_descriptors: list[InteractiveWorldOwnerDescriptor] = []
    for expected_id, module_name, attribute_name, _ in sorted(WORLD_OWNER_IMPORTS, key=lambda owner: owner[0]):
        try:
            owner_module = import_module(module_name)
        except ImportError as error:
            raise CatalogueValidationError((f"world owner {expected_id} cannot be imported: {module_name}",)) from error
        descriptor = getattr(owner_module, attribute_name, None)
        if not isinstance(descriptor, InteractiveWorldOwnerDescriptor):
            raise CatalogueValidationError((f"world owner {expected_id} has an invalid descriptor",))
        if descriptor.task_world_id != expected_id:
            raise CatalogueValidationError((f"world owner list ID does not match its descriptor: {expected_id}",))
        world_descriptors.append(descriptor)

    lifecycle_descriptors: list[LifecycleOwnerDescriptor] = []
    for expected_id, module_name, attribute_name, _ in sorted(LIFECYCLE_OWNER_IMPORTS, key=lambda owner: owner[0]):
        try:
            owner_module = import_module(module_name)
        except ImportError as error:
            raise CatalogueValidationError(
                (f"lifecycle owner {expected_id} cannot be imported: {module_name}",)
            ) from error
        descriptor = getattr(owner_module, attribute_name, None)
        if not isinstance(descriptor, LifecycleOwnerDescriptor):
            raise CatalogueValidationError((f"lifecycle owner {expected_id} has an invalid descriptor",))
        if descriptor.definition.metadata.template_id != expected_id:
            raise CatalogueValidationError((f"lifecycle owner list ID does not match its descriptor: {expected_id}",))
        lifecycle_descriptors.append(descriptor)

    return tuple(world_descriptors), tuple(lifecycle_descriptors)


def _source_definitions(
    world_descriptors: tuple[InteractiveWorldOwnerDescriptor, ...],
    lifecycle_descriptors: tuple[LifecycleOwnerDescriptor, ...],
) -> tuple[tuple[InteractiveWorldDefinition, ...], tuple[LifecycleDefinition, ...]]:
    """Load definitions through explicit owner descriptors before generation."""

    worlds: list[InteractiveWorldDefinition] = []
    for world_descriptor in world_descriptors:
        try:
            worlds.append(world_descriptor.load())
        except (ImportError, AttributeError, TypeError, ValueError) as error:
            raise CatalogueValidationError(
                (f"world owner factory is invalid: {world_descriptor.task_world_id}: {error}",)
            ) from error
    lifecycles: list[LifecycleDefinition] = []
    for lifecycle_descriptor in lifecycle_descriptors:
        try:
            lifecycles.append(lifecycle_descriptor.load())
        except (ImportError, AttributeError, TypeError, ValueError) as error:
            template_id = lifecycle_descriptor.definition.metadata.template_id
            raise CatalogueValidationError(
                (f"lifecycle owner definition is invalid: {template_id}: {error}",)
            ) from error
    return tuple(worlds), tuple(lifecycles)


def _current_definitions() -> tuple[tuple[InteractiveWorldDefinition, ...], tuple[LifecycleDefinition, ...]]:
    world_descriptors, lifecycle_descriptors = _source_descriptors()
    return _source_definitions(world_descriptors, lifecycle_descriptors)


def _identity_payload(identity: Any) -> dict[str, Any]:
    return {
        "id": str(identity.id),
        "key": str(identity.key),
        "version": identity.version,
    }


def _world_entry(definition: InteractiveWorldDefinition) -> dict[str, Any]:
    return {
        "kind": "world",
        **_identity_payload(definition.identity),
        "task_world_id": definition.build.task_world_id,
        "title": definition.title,
        "summary": definition.summary,
        "domain": definition.domain,
        "tags": list(definition.tags),
        "capabilities": sorted(definition.capabilities),
    }


def _profile_entry(definition: InteractiveWorldDefinition, index: int) -> dict[str, Any]:
    identity = definition.profile_identities[index]
    metadata = definition.profile_metadata[index]
    return {
        "kind": "profile",
        **_identity_payload(identity),
        "parent_id": str(identity.parent_id),
        "registration_id": identity.registration_id,
        "task_world_id": definition.build.task_world_id,
        "profile_id": metadata.profile_id,
        "title": metadata.title,
        "summary": metadata.summary,
        "category": metadata.category,
        "difficulty": metadata.difficulty.value,
        "lifecycle": metadata.lifecycle.value,
        "visibility": metadata.visibility.value,
        "tags": list(metadata.tags),
    }


def _lifecycle_entry(definition: LifecycleDefinition) -> dict[str, Any]:
    metadata = definition.metadata
    return {
        "kind": "lifecycle",
        **_identity_payload(definition.identity),
        "template_id": metadata.template_id,
        "name": metadata.name,
        "discipline": metadata.discipline,
    }


def _variant_entry(definition: LifecycleDefinition, identity: Any) -> dict[str, Any]:
    return {
        "kind": "variant",
        **_identity_payload(identity),
        "parent_id": str(identity.parent_id),
        "registration_id": identity.registration_id,
        "template_id": definition.metadata.template_id,
    }


def semantic_snapshot(
    worlds: tuple[InteractiveWorldDefinition, ...] | None = None,
    lifecycles: tuple[LifecycleDefinition, ...] | None = None,
) -> dict[str, Any]:
    """Return deterministic, non-hash semantic entries for current catalogues."""

    loaded_worlds: tuple[InteractiveWorldDefinition, ...] = ()
    loaded_lifecycles: tuple[LifecycleDefinition, ...] = ()
    if worlds is None or lifecycles is None:
        loaded_worlds, loaded_lifecycles = _current_definitions()
    current_worlds = loaded_worlds if worlds is None else worlds
    current_lifecycles = loaded_lifecycles if lifecycles is None else lifecycles
    world_entries: list[dict[str, Any]] = []
    profile_entries: list[dict[str, Any]] = []
    for definition in sorted(current_worlds, key=lambda item: item.build.task_world_id):
        world_entries.append(_world_entry(definition))
        profile_entries.extend(_profile_entry(definition, index) for index in range(len(definition.profile_identities)))
    lifecycle_entries: list[dict[str, Any]] = [
        _lifecycle_entry(definition)
        for definition in sorted(current_lifecycles, key=lambda item: item.metadata.template_id)
    ]
    variant_entries: list[dict[str, Any]] = [
        _variant_entry(definition, identity)
        for definition in sorted(current_lifecycles, key=lambda item: item.metadata.template_id)
        for identity in definition.variant_identities
    ]
    return {
        "schema_version": 1,
        "worlds": world_entries,
        "profiles": profile_entries,
        "lifecycles": lifecycle_entries,
        "variants": variant_entries,
    }


def _validate_descriptor_signature(descriptor: Any, label: str) -> str | None:
    try:
        signature = inspect.signature(descriptor.load)
    except (AttributeError, TypeError, ValueError) as error:
        return f"{label} descriptor load signature is not inspectable: {error}"
    required = [
        parameter.name
        for parameter in signature.parameters.values()
        if parameter.default is inspect.Parameter.empty
        and parameter.kind
        in (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.KEYWORD_ONLY)
    ]
    if required:
        return f"{label} descriptor load requires arguments: {', '.join(required)}"
    return None


def validate_catalogues(
    worlds: tuple[InteractiveWorldDefinition, ...],
    lifecycles: tuple[LifecycleDefinition, ...],
    *,
    world_descriptors: tuple[InteractiveWorldOwnerDescriptor, ...] | None = None,
    lifecycle_descriptors: tuple[LifecycleOwnerDescriptor, ...] | None = None,
) -> None:
    """Validate descriptor shape, identity, metadata, and stable ordering."""

    errors: list[str] = []
    if world_descriptors is None:
        from aec_bench.worlds.generated_catalogue import WORLD_DESCRIPTORS

        world_descriptors = WORLD_DESCRIPTORS
    if lifecycle_descriptors is None:
        from aec_bench.lifecycles.generated_catalogue import LIFECYCLE_DESCRIPTORS

        lifecycle_descriptors = LIFECYCLE_DESCRIPTORS
    world_ids = tuple(
        getattr(descriptor, "task_world_id", f"<invalid-{index}>") for index, descriptor in enumerate(world_descriptors)
    )
    if world_ids != tuple(sorted(world_ids)):
        errors.append("world descriptor order is not stable")
    lifecycle_ids_list: list[Any | str] = []
    for index, lifecycle_descriptor in enumerate(lifecycle_descriptors):
        metadata = getattr(getattr(lifecycle_descriptor, "definition", None), "metadata", None)
        lifecycle_ids_list.append(metadata.template_id if metadata is not None else f"<invalid-{index}>")
    lifecycle_ids = tuple(lifecycle_ids_list)
    if lifecycle_ids != tuple(sorted(lifecycle_ids)):
        errors.append("lifecycle descriptor order is not stable")
    if len(world_ids) != len(set(world_ids)):
        errors.append("world task-world IDs must be unique")
    if len(lifecycle_ids) != len(set(lifecycle_ids)):
        errors.append("lifecycle template IDs must be unique")
    for index, world_descriptor in enumerate(world_descriptors):
        if not isinstance(world_descriptor, InteractiveWorldOwnerDescriptor):
            errors.append(f"world descriptor {index} has an invalid type")
        signature_error = _validate_descriptor_signature(world_descriptor, f"world {world_ids[index]}")
        if signature_error:
            errors.append(signature_error)
    for index, lifecycle_descriptor in enumerate(lifecycle_descriptors):
        if not isinstance(lifecycle_descriptor, LifecycleOwnerDescriptor):
            errors.append(f"lifecycle descriptor {index} has an invalid type")
        signature_error = _validate_descriptor_signature(lifecycle_descriptor, f"lifecycle {index}")
        if signature_error:
            errors.append(signature_error)

    identities: list[Any] = []
    registration_ids: list[tuple[str, str]] = []
    for definition in worlds:
        identities.append(definition.identity)
        if definition.build.task_world_id != definition.ref.task_world_id:
            errors.append(f"world {definition.build.task_world_id} has an invalid build reference")
        if any(not isinstance(capability, str) or not capability.strip() for capability in definition.capabilities):
            errors.append(f"world {definition.build.task_world_id} capabilities contain non-string values")
        for identity in definition.profile_identities:
            identities.append(identity)
            registration_ids.append((str(identity.parent_id), identity.registration_id))
            if identity.version <= 0:
                errors.append(f"profile {identity.registration_id} version must be positive")
    for lifecycle_definition in lifecycles:
        identities.append(lifecycle_definition.identity)
        for identity in lifecycle_definition.variant_identities:
            identities.append(identity)
            registration_ids.append((str(identity.parent_id), identity.registration_id))
            if identity.version <= 0:
                errors.append(f"variant {identity.registration_id} version must be positive")
    if len(identities) != len({identity.id for identity in identities}):
        errors.append("entity UUIDs must be unique")
    if len(identities) != len({identity.key for identity in identities}):
        errors.append("entity keys must be unique")
    if len(registration_ids) != len(set(registration_ids)):
        errors.append("member registration IDs must be unique within each parent")
    for identity in identities:
        if identity.version <= 0:
            errors.append(f"entity {identity.key} version must be positive")
    world_definition_ids = tuple(definition.build.task_world_id for definition in worlds)
    if world_definition_ids != tuple(sorted(world_definition_ids)):
        errors.append("world definitions are not in stable order")
    lifecycle_definition_ids = tuple(definition.metadata.template_id for definition in lifecycles)
    if lifecycle_definition_ids != tuple(sorted(lifecycle_definition_ids)):
        errors.append("lifecycle definitions are not in stable order")
    if set(world_ids) != set(world_definition_ids):
        errors.append("world descriptors do not match loaded definitions")
    if set(lifecycle_ids) != set(lifecycle_definition_ids):
        errors.append("lifecycle descriptors do not match loaded definitions")
    if errors:
        raise CatalogueValidationError(errors)


def _write_catalogue(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_catalogues(root: Path = _REPO_ROOT, snapshot_path: Path | None = None) -> dict[str, Any]:
    """Write both generated catalogues and return a semantic build summary."""

    world_descriptors, lifecycle_descriptors = _source_descriptors()
    worlds, lifecycles = _source_definitions(world_descriptors, lifecycle_descriptors)
    validate_catalogues(
        worlds,
        lifecycles,
        world_descriptors=world_descriptors,
        lifecycle_descriptors=lifecycle_descriptors,
    )
    world_path, lifecycle_path = catalogue_paths(root)
    _write_catalogue(world_path, render_world_catalogue(WORLD_OWNER_IMPORTS))
    _write_catalogue(lifecycle_path, render_lifecycle_catalogue(LIFECYCLE_OWNER_IMPORTS))
    snapshot = semantic_snapshot(worlds, lifecycles)
    if snapshot_path is not None:
        _write_catalogue(snapshot_path, json.dumps(snapshot, indent=2, sort_keys=True) + "\n")
    return {
        "status": "built",
        "files": [str(world_path), str(lifecycle_path)],
        "worlds": len(snapshot["worlds"]),
        "profiles": len(snapshot["profiles"]),
        "lifecycles": len(snapshot["lifecycles"]),
        "variants": len(snapshot["variants"]),
        "snapshot_path": None if snapshot_path is None else str(snapshot_path),
    }


def check_catalogues(root: Path = _REPO_ROOT) -> dict[str, Any]:
    """Check generated freshness and current semantic catalogue validity."""

    world_descriptors, lifecycle_descriptors = _source_descriptors()
    worlds, lifecycles = _source_definitions(world_descriptors, lifecycle_descriptors)
    validate_catalogues(
        worlds,
        lifecycles,
        world_descriptors=world_descriptors,
        lifecycle_descriptors=lifecycle_descriptors,
    )
    world_path, lifecycle_path = catalogue_paths(root)
    with tempfile.TemporaryDirectory(prefix="aec-bench-catalogue-") as temp_dir:
        temp_world, temp_lifecycle = catalogue_paths(Path(temp_dir))
        _write_catalogue(temp_world, render_world_catalogue(WORLD_OWNER_IMPORTS))
        _write_catalogue(temp_lifecycle, render_lifecycle_catalogue(LIFECYCLE_OWNER_IMPORTS))
        stale = []
        for committed, generated in ((world_path, temp_world), (lifecycle_path, temp_lifecycle)):
            if not committed.is_file():
                stale.append(f"missing generated catalogue: {committed}")
            elif committed.read_bytes() != generated.read_bytes():
                stale.append(f"generated catalogue is stale: {committed}")
    if stale:
        raise CatalogueValidationError(stale)
    snapshot = semantic_snapshot(worlds, lifecycles)
    return {
        "status": "ok",
        "files": [str(world_path), str(lifecycle_path)],
        "worlds": len(snapshot["worlds"]),
        "profiles": len(snapshot["profiles"]),
        "lifecycles": len(snapshot["lifecycles"]),
        "variants": len(snapshot["variants"]),
    }


def _load_snapshot_source(source: str) -> dict[str, Any]:
    path = Path(source)
    if not path.is_file():
        raise CatalogueError(f"catalogue snapshot does not exist: {source}")
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise CatalogueError(f"catalogue snapshot is not valid JSON: {source}") from error
    if not isinstance(document, dict):
        raise CatalogueError(f"catalogue snapshot is not a JSON object: {source}")
    return cast(dict[str, Any], document)


def _flatten_snapshot(snapshot: Mapping[str, Any]) -> dict[tuple[str, str], dict[str, Any]]:
    if snapshot.get("schema_version") != 1:
        raise CatalogueError("catalogue snapshot schema_version must be 1")
    flattened: dict[tuple[str, str], dict[str, Any]] = {}
    seen_ids: set[str] = set()
    seen_keys: set[str] = set()
    expected_kinds = {
        "worlds": "world",
        "profiles": "profile",
        "lifecycles": "lifecycle",
        "variants": "variant",
    }
    for collection, expected_kind in expected_kinds.items():
        entries = snapshot.get(collection)
        if not isinstance(entries, list):
            raise CatalogueError(f"catalogue snapshot field {collection!r} must be a list")
        for entry in entries:
            if (
                not isinstance(entry, dict)
                or entry.get("kind") != expected_kind
                or not isinstance(entry.get("id"), str)
                or not entry["id"].strip()
                or not isinstance(entry.get("key"), str)
                or not entry["key"].strip()
                or isinstance(entry.get("version"), bool)
                or not isinstance(entry.get("version"), int)
                or entry["version"] <= 0
            ):
                raise CatalogueError(f"catalogue snapshot field {collection!r} has an invalid entry")
            if entry["id"] in seen_ids:
                raise CatalogueError(f"catalogue snapshot has duplicate entity identity: {entry['id']}")
            if entry["key"] in seen_keys:
                raise CatalogueError(f"catalogue snapshot has duplicate entity key: {entry['key']}")
            seen_ids.add(entry["id"])
            seen_keys.add(entry["key"])
            entity_key = (entry["kind"], entry["id"])
            flattened[entity_key] = entry
    return flattened


def diff_catalogue(source: str) -> dict[str, Any]:
    """Compare current semantic entries with a JSON snapshot."""

    previous = _flatten_snapshot(_load_snapshot_source(source))
    current = _flatten_snapshot(semantic_snapshot())
    added = [current[key] for key in sorted(current.keys() - previous.keys())]
    removed = [previous[key] for key in sorted(previous.keys() - current.keys())]
    changed = []
    for key in sorted(current.keys() & previous.keys()):
        before = previous[key]
        after = current[key]
        if after["version"] < before["version"]:
            raise CatalogueValidationError(
                (f"catalogue entity version regressed: {after['key']} {before['version']} -> {after['version']}",)
            )
        fields = {
            field: {"before": before.get(field), "after": after.get(field)}
            for field in sorted(set(before) | set(after))
            if field not in {"kind", "id"} and before.get(field) != after.get(field)
        }
        if fields:
            changed.append(
                {
                    "kind": key[0],
                    "id": key[1],
                    "key": after.get("key", before.get("key")),
                    "fields": fields,
                }
            )
    return {"against": source, "added": added, "changed": changed, "removed": removed}


__all__ = (
    "LIFECYCLE_OWNER_IMPORTS",
    "WORLD_OWNER_IMPORTS",
    "CatalogueError",
    "CatalogueValidationError",
    "build_catalogues",
    "catalogue_paths",
    "check_catalogues",
    "diff_catalogue",
    "render_lifecycle_catalogue",
    "render_world_catalogue",
    "semantic_snapshot",
    "validate_catalogues",
)
