# ABOUTME: Self-contained HTML report renderer for evolution run results.
# ABOUTME: Produces a single HTML file with inline SVG chart and collapsible artifact diffs.

from __future__ import annotations

import html
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aec_bench.evolution.report_data import CycleReport, EvolutionReportData


def render_evolution_report_html(data: EvolutionReportData) -> str:
    """Render a self-contained HTML report from evolution data."""
    cycles_html = "\n".join(_render_cycle_card(c) for c in data.cycles)
    chart_html = _render_svg_chart(data)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Evolution Report — {_esc(data.workspace_name)}</title>
{_CSS}
</head>
<body>

<header>
  <h1>Evolution Report</h1>
  <p class="subtitle">{_esc(data.workspace_name)}</p>
</header>

<main>
  {_render_overview(data)}
  {chart_html}
  <section class="cycles">
    {cycles_html if cycles_html else '<p class="empty">No evolution cycles recorded.</p>'}
  </section>
</main>

<footer>
  <p>Generated by aec-bench evolution engine</p>
</footer>

{_JS}
</body>
</html>"""


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------


def _render_overview(data: EvolutionReportData) -> str:
    status_class = "converged" if data.converged else "running"
    status_text = "Converged" if data.converged else "Not converged"
    return f"""\
<section class="overview">
  <div class="stat-grid">
    <div class="stat">
      <span class="stat-label">Cycles</span>
      <span class="stat-value">{data.total_cycles}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Best Score</span>
      <span class="stat-value score">{data.best_score:.1%}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Final Score</span>
      <span class="stat-value score">{data.final_score:.1%}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Status</span>
      <span class="stat-value {status_class}">{status_text}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Model</span>
      <span class="stat-value model">{_esc(data.model)}</span>
    </div>
  </div>
</section>"""


def _render_svg_chart(data: EvolutionReportData) -> str:
    if not data.cycles:
        return ""

    scores = [0.0] + [c.score for c in data.cycles]
    labels = ["evo-0"] + [c.version_tag for c in data.cycles]
    n = len(scores)
    if n < 2:
        return ""

    # Chart dimensions
    w, h = 700, 200
    pad_x, pad_y = 50, 30
    plot_w = w - 2 * pad_x
    plot_h = h - 2 * pad_y

    max_score = max(max(scores), 0.01)

    def _x(i: int) -> float:
        return pad_x + (i / (n - 1)) * plot_w

    def _y(s: float) -> float:
        return h - pad_y - (s / max_score) * plot_h

    # Build polyline points
    points = " ".join(f"{_x(i):.1f},{_y(s):.1f}" for i, s in enumerate(scores))

    # Build dots and labels
    dots = []
    for i, (s, label) in enumerate(zip(scores, labels, strict=True)):
        cx, cy = _x(i), _y(s)
        click = f' onclick="scrollToCycle({i})" style="cursor:pointer"' if i > 0 else ""
        label_y = cy - 12
        dots.append(
            f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="5" class="dot"{click}/>'
            f'<text x="{cx:.1f}" y="{label_y:.1f}" class="score-label">'
            f"{s:.1%}</text>"
            f'<text x="{cx:.1f}" y="{h - 5}" class="tag-label">'
            f"{_esc(label)}</text>"
        )

    return f"""\
<section class="chart">
  <h2>Score Trajectory</h2>
  <svg viewBox="0 0 {w} {h}" class="score-chart">
    <line x1="{pad_x}" y1="{h - pad_y}" x2="{w - pad_x}" y2="{h - pad_y}"
          stroke="#ccc" stroke-width="1"/>
    <line x1="{pad_x}" y1="{pad_y}" x2="{pad_x}" y2="{h - pad_y}"
          stroke="#ccc" stroke-width="1"/>
    <polyline points="{points}" class="score-line"/>
    {"".join(dots)}
  </svg>
</section>"""


def _render_cycle_card(cycle: CycleReport) -> str:
    skills_html = _render_skills_section(cycle)
    prompt_html = (
        _render_collapsible(
            "System Prompt Diff",
            _render_diff_block(cycle.prompt_diff),
            collapsed=True,
        )
        if cycle.prompt_diff
        else ""
    )

    reasoning_html = ""
    if cycle.evolver_reasoning:
        reasoning_html = f"""\
<div class="reasoning">
  <span class="section-label">Evolver Reasoning</span>
  <blockquote>{_esc(cycle.evolver_reasoning)}</blockquote>
</div>"""

    return f"""\
<article class="cycle-card" id="cycle-{cycle.cycle}">
  <div class="cycle-header">
    <h3>Cycle {cycle.cycle}</h3>
    <span class="version-tag">{_esc(cycle.version_tag)}</span>
    <span class="score-badge">{cycle.score:.1%}</span>
  </div>
  {prompt_html}
  {skills_html}
  {reasoning_html}
</article>"""


def _render_skills_section(cycle: CycleReport) -> str:
    if not cycle.skills_added and not cycle.skills_modified and not cycle.skills_removed:
        return ""

    pills: list[str] = []
    for name in cycle.skills_added:
        diff = cycle.skill_diffs.get(name, "")
        if diff:
            pills.append(
                _render_collapsible(
                    f'<span class="pill added">+ {_esc(name)}</span>',
                    _render_diff_block(diff),
                    collapsed=True,
                )
            )
        else:
            pills.append(f'<span class="pill added">+ {_esc(name)}</span>')

    for name in cycle.skills_modified:
        diff = cycle.skill_diffs.get(name, "")
        if diff:
            pills.append(
                _render_collapsible(
                    f'<span class="pill modified">~ {_esc(name)}</span>',
                    _render_diff_block(diff),
                    collapsed=True,
                )
            )
        else:
            pills.append(f'<span class="pill modified">~ {_esc(name)}</span>')

    for name in cycle.skills_removed:
        pills.append(f'<span class="pill removed">- {_esc(name)}</span>')

    return f"""\
<div class="skills-section">
  <span class="section-label">Skills</span>
  <div class="skills-list">
    {"".join(pills)}
  </div>
</div>"""


def _render_collapsible(summary: str, content: str, *, collapsed: bool = True) -> str:
    state = "" if collapsed else " open"
    return f"""\
<details{state}>
  <summary>{summary}</summary>
  <div class="collapsible-content">{content}</div>
</details>"""


def _render_diff_block(diff_text: str) -> str:
    if not diff_text:
        return '<pre class="diff empty">No changes</pre>'

    lines: list[str] = []
    for line in diff_text.splitlines():
        escaped = _esc(line)
        if line.startswith("+") and not line.startswith("+++"):
            lines.append(f'<span class="diff-add">{escaped}</span>')
        elif line.startswith("-") and not line.startswith("---"):
            lines.append(f'<span class="diff-del">{escaped}</span>')
        elif line.startswith("@@"):
            lines.append(f'<span class="diff-hunk">{escaped}</span>')
        else:
            lines.append(escaped)

    return f'<pre class="diff">{"<br>".join(lines)}</pre>'


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _esc(text: str) -> str:
    return html.escape(text)


# ---------------------------------------------------------------------------
# Inline CSS
# ---------------------------------------------------------------------------

_CSS = """\
<style>
  :root {
    --bg: #f6f4ef;
    --card-bg: #ffffff;
    --text: #2c2c2c;
    --text-muted: #888;
    --green: #4a6741;
    --red: #BF4D43;
    --amber: #D4A27F;
    --blue: #61AAF2;
    --border: #e0ddd6;
    --code-bg: #1e1e1e;
    --code-text: #d4d4d4;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: var(--bg);
    color: var(--text);
    max-width: 900px;
    margin: 0 auto;
    padding: 24px 16px;
    line-height: 1.5;
  }
  header { margin-bottom: 32px; }
  header h1 { font-size: 1.8em; font-weight: 700; }
  header .subtitle { color: var(--text-muted); font-size: 1.1em; }
  footer { margin-top: 48px; text-align: center; color: var(--text-muted); font-size: 0.85em; }

  /* Overview */
  .overview { margin-bottom: 32px; }
  .stat-grid {
    display: flex; flex-wrap: wrap; gap: 16px;
  }
  .stat {
    background: var(--card-bg); border: 1px solid var(--border);
    border-radius: 8px; padding: 12px 20px;
    display: flex; flex-direction: column; min-width: 120px;
  }
  .stat-label { font-size: 0.75em; text-transform: uppercase; color: var(--text-muted); }
  .stat-value { font-size: 1.3em; font-weight: 600; }
  .stat-value.score { color: var(--green); }
  .stat-value.converged { color: var(--green); }
  .stat-value.running { color: var(--amber); }
  .stat-value.model { font-size: 0.9em; font-family: 'JetBrains Mono', monospace; }

  /* Chart */
  .chart { margin-bottom: 32px; }
  .chart h2 { font-size: 1.2em; margin-bottom: 12px; }
  .score-chart {
    width: 100%; height: auto;
    background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px;
  }
  .score-line { fill: none; stroke: var(--green); stroke-width: 2.5; }
  .dot { fill: var(--green); }
  .dot:hover { fill: var(--blue); r: 7; }
  .score-label { font-size: 11px; fill: var(--text); text-anchor: middle; font-weight: 600; }
  .tag-label { font-size: 10px; fill: var(--text-muted); text-anchor: middle; }

  /* Cycle cards */
  .cycles { display: flex; flex-direction: column; gap: 20px; }
  .cycle-card {
    background: var(--card-bg); border: 1px solid var(--border);
    border-radius: 8px; padding: 20px;
  }
  .cycle-header {
    display: flex; align-items: center; gap: 12px; margin-bottom: 16px;
  }
  .cycle-header h3 { font-size: 1.15em; }
  .version-tag {
    font-family: 'JetBrains Mono', monospace; font-size: 0.8em;
    background: var(--bg); padding: 2px 8px; border-radius: 4px;
    color: var(--text-muted);
  }
  .score-badge {
    margin-left: auto; font-weight: 700; font-size: 1.1em;
    color: var(--green);
  }

  /* Section labels */
  .section-label {
    display: block; font-size: 0.75em; text-transform: uppercase;
    color: var(--text-muted); margin-bottom: 6px;
  }

  /* Skills */
  .skills-section { margin-bottom: 12px; }
  .skills-list { display: flex; flex-wrap: wrap; gap: 6px; }
  .pill {
    display: inline-block; padding: 3px 12px; border-radius: 14px;
    font-size: 0.82em; font-weight: 500; color: white; cursor: default;
  }
  .pill.added { background: var(--green); }
  .pill.modified { background: var(--amber); color: var(--text); }
  .pill.removed { background: var(--red); }

  /* Collapsible */
  details { margin-bottom: 10px; }
  details summary {
    cursor: pointer; user-select: none; list-style: none;
  }
  details summary::-webkit-details-marker { display: none; }
  details summary::before {
    content: '\\25B6'; display: inline-block; margin-right: 6px;
    font-size: 0.7em; transition: transform 0.15s;
  }
  details[open] summary::before { transform: rotate(90deg); }
  .collapsible-content { margin-top: 8px; }

  /* Diffs */
  .diff {
    background: var(--code-bg); color: var(--code-text);
    padding: 12px; border-radius: 6px; overflow-x: auto;
    font-family: 'JetBrains Mono', monospace; font-size: 0.8em;
    line-height: 1.6; max-height: 400px; overflow-y: auto;
  }
  .diff-add { color: #98c379; }
  .diff-del { color: #e06c75; }
  .diff-hunk { color: #61afef; }

  /* Reasoning */
  .reasoning { margin-top: 12px; }
  .reasoning blockquote {
    border-left: 3px solid var(--amber); padding: 8px 14px;
    background: var(--bg); border-radius: 0 6px 6px 0;
    font-style: italic; color: #555;
  }

  .empty { text-align: center; color: var(--text-muted); padding: 40px; }
</style>"""

# ---------------------------------------------------------------------------
# Inline JS
# ---------------------------------------------------------------------------

_JS = """\
<script>
function scrollToCycle(n) {
  var el = document.getElementById('cycle-' + n);
  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
</script>"""
