# ABOUTME: Exposes phase-neutral program-necessity contracts and reducers.
# ABOUTME: Keeps historical import paths stable while the capability lives in a package.

from aec_bench.experimentation.qualification.program_necessity.contracts import (
    ProgramComplexityDerivationRef,
    ProgramComplexityEvidence,
    ProgramNecessityArm,
    ProgramNecessityArmTemplateRef,
    ProgramNecessityDesign,
    ProgramNecessityExecutionScheduleRef,
    ProgramNecessityFamilyPlan,
    ProgramNecessityLineageCandidateRef,
    ProgramNecessityLineageContrast,
    ProgramNecessityLineagePlan,
    ProgramNecessityLineageRole,
    ProgramNecessityMeasurementPolicy,
    ProgramNecessityMechanism,
    ProgramNecessityMissingDataPolicy,
    ProgramNecessityObservation,
    ProgramNecessityOpeningPolicy,
    ProgramNecessityPreregistration,
    ProgramNecessityProblemViewRef,
    ProgramNecessityStudyPlan,
    ProgramNecessityStudyRef,
    ProgramTopologyProfile,
    ShamMatchAttestation,
)
from aec_bench.experimentation.qualification.program_necessity.reducer import (
    ProgramNecessityFamilyResult,
    ProgramNecessityGateResult,
    ProgramNecessityStudyResult,
    build_program_necessity_family_result,
    evaluate_program_necessity_gate,
    evaluate_program_necessity_study,
)

__all__ = [
    "ProgramComplexityDerivationRef",
    "ProgramComplexityEvidence",
    "ProgramNecessityArm",
    "ProgramNecessityArmTemplateRef",
    "ProgramNecessityDesign",
    "ProgramNecessityExecutionScheduleRef",
    "ProgramNecessityFamilyPlan",
    "ProgramNecessityFamilyResult",
    "ProgramNecessityGateResult",
    "ProgramNecessityLineageCandidateRef",
    "ProgramNecessityLineageContrast",
    "ProgramNecessityLineagePlan",
    "ProgramNecessityLineageRole",
    "ProgramNecessityMeasurementPolicy",
    "ProgramNecessityMechanism",
    "ProgramNecessityMissingDataPolicy",
    "ProgramNecessityObservation",
    "ProgramNecessityOpeningPolicy",
    "ProgramNecessityPreregistration",
    "ProgramNecessityProblemViewRef",
    "ProgramNecessityStudyPlan",
    "ProgramNecessityStudyRef",
    "ProgramNecessityStudyResult",
    "ProgramTopologyProfile",
    "ShamMatchAttestation",
    "build_program_necessity_family_result",
    "evaluate_program_necessity_gate",
    "evaluate_program_necessity_study",
]
