# ABOUTME: Converts a JPEG image to ANSI half-block art using Rich markup for 24-bit colour.
# ABOUTME: Outputs a Python module with a PIXEL_ART constant for use in the TUI landing screen.

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image


def rgb_to_hex(r: int, g: int, b: int) -> str:
    """Convert RGB tuple to hex colour string."""
    return f"#{r:02x}{g:02x}{b:02x}"


def is_near_white(r: int, g: int, b: int, threshold: int = 230) -> bool:
    """Return True if all RGB channels exceed the background threshold."""
    return r > threshold and g > threshold and b > threshold


def image_to_half_block_lines(
    img: Image.Image,
    width: int,
    bg_threshold: int = 230,
) -> list[str]:
    """Convert a PIL Image to Rich-markup half-block art lines.

    Uses Unicode half-block characters (upper-half ▀, lower-half ▄, full █,
    and space) paired with Rich ``[#rrggbb]`` / ``[#rrggbb on #rrggbb]``
    colour tags to produce 24-bit terminal art.

    Pixels whose RGB channels all exceed *bg_threshold* are treated as
    transparent (rendered as a plain space).
    """
    # Resize keeping aspect ratio.  Each character cell is ~2:1 (height:width),
    # and we pack two pixel rows per character row using half-blocks.
    aspect = img.height / img.width
    height = int(width * aspect)
    # Ensure height is even so we can pair rows cleanly.
    height = height if height % 2 == 0 else height + 1
    img = img.resize((width, height), Image.LANCZOS)
    pixels = img.load()

    lines: list[str] = []

    for y in range(0, height, 2):
        parts: list[str] = []
        for x in range(width):
            top_r, top_g, top_b = pixels[x, y][:3]
            bot_r, bot_g, bot_b = pixels[x, y + 1][:3]

            top_white = is_near_white(top_r, top_g, top_b, bg_threshold)
            bot_white = is_near_white(bot_r, bot_g, bot_b, bg_threshold)

            if top_white and bot_white:
                # Both transparent → space.
                parts.append(" ")
            elif top_white:
                # Top transparent, bottom coloured → lower-half block.
                colour = rgb_to_hex(bot_r, bot_g, bot_b)
                parts.append(f"[{colour}]▄[/]")
            elif bot_white:
                # Top coloured, bottom transparent → upper-half block.
                colour = rgb_to_hex(top_r, top_g, top_b)
                parts.append(f"[{colour}]▀[/]")
            else:
                # Both coloured → upper-half with fg=top, bg=bottom.
                top_hex = rgb_to_hex(top_r, top_g, top_b)
                bot_hex = rgb_to_hex(bot_r, bot_g, bot_b)
                if top_hex == bot_hex:
                    parts.append(f"[{top_hex}]█[/]")
                else:
                    parts.append(f"[{top_hex} on {bot_hex}]▀[/]")

        lines.append("".join(parts))

    return lines


def write_pixel_art_module(lines: list[str], output_path: Path) -> None:
    """Write the converted pixel art as a Python module constant."""
    escaped_lines = [line.replace("\\", "\\\\").replace('"', '\\"') for line in lines]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w") as fh:
        fh.write(
            "# ABOUTME: Contains pre-rendered pixel-art and ASCII-title"
            " constants for the TUI landing screen.\n"
            "# ABOUTME: Generated by scripts/convert_pixel_art.py"
            " from the project mascot image.\n"
            "\n"
            "PIXEL_ART = (\n"
        )
        for line in escaped_lines:
            fh.write(f'    "{line}\\n"\n')
        fh.write(")\n")

    print(f"Wrote {len(lines)} lines to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert a JPEG image to Rich half-block pixel art.",
    )
    parser.add_argument(
        "--input",
        default="download.jpeg",
        help="Path to the input image (default: download.jpeg)",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=40,
        help="Output width in character columns (default: 40)",
    )
    parser.add_argument(
        "--bg-threshold",
        type=int,
        default=230,
        help="RGB channel threshold for near-white detection (default: 230)",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Print to terminal instead of writing a Python module",
    )
    args = parser.parse_args()

    img_path = Path(args.input)
    if not img_path.exists():
        print(f"Error: image not found at {img_path}", file=sys.stderr)
        sys.exit(1)

    img = Image.open(img_path).convert("RGB")
    lines = image_to_half_block_lines(img, width=args.width, bg_threshold=args.bg_threshold)

    if args.preview:
        from rich.console import Console

        console = Console()
        for line in lines:
            console.print(line, highlight=False)
    else:
        output_path = Path("src/aec_bench/tui/assets/pixel_art.py")
        write_pixel_art_module(lines, output_path)


if __name__ == "__main__":
    main()
