# ABOUTME: Feedback package for structured expert review workflows in aec-bench.
# ABOUTME: This package will persist annotations and route adjudicated signals back.

from aec_bench.feedback.adjudication import adjudicate_trial_feedback
from aec_bench.feedback.annotation_consumer import (
    build_evaluation_feedback_handoff,
    read_feedback_annotations,
    read_feedback_items,
    read_latest_adjudication,
    read_reviewer_profile,
    read_reviewer_profiles,
    write_adjudication_record,
    write_calibration_result,
    write_feedback_annotation,
    write_feedback_item,
    write_reviewer_profile,
)
from aec_bench.feedback.assignment import build_reviewer_queue
from aec_bench.feedback.calibration import apply_calibration_result, score_reviewer_calibration
from aec_bench.feedback.models import (
    AdjudicationRecord,
    AdjudicationStatus,
    CalibrationReference,
    CalibrationStatus,
    EvaluationFeedbackHandoff,
    FeedbackAnnotation,
    FeedbackItem,
    FeedbackItemStatus,
    FeedbackItemType,
    ReviewAssignment,
    ReviewerCalibrationResult,
    ReviewerProfile,
    ReviewerWeighting,
)
from aec_bench.feedback.review_service import (
    ReviewAccessError,
    ReviewError,
    ReviewNotFoundError,
    ReviewQueueSnapshot,
    ReviewTrialBundle,
    adjudicate_review_trial,
    load_review_bundle,
    load_review_queue,
    persist_feedback_annotation,
    score_review_calibration,
    submit_review_annotation,
)
from aec_bench.feedback.signals import build_feedback_confidence, generate_feedback_items
from aec_bench.feedback.textual_app import ReviewTerminalApp

__all__ = [
    "AdjudicationRecord",
    "AdjudicationStatus",
    "CalibrationReference",
    "CalibrationStatus",
    "EvaluationFeedbackHandoff",
    "FeedbackAnnotation",
    "FeedbackItem",
    "FeedbackItemStatus",
    "FeedbackItemType",
    "ReviewAssignment",
    "ReviewerCalibrationResult",
    "ReviewerProfile",
    "ReviewerWeighting",
    "ReviewAccessError",
    "ReviewError",
    "ReviewNotFoundError",
    "ReviewQueueSnapshot",
    "ReviewTerminalApp",
    "ReviewTrialBundle",
    "adjudicate_review_trial",
    "adjudicate_trial_feedback",
    "apply_calibration_result",
    "build_evaluation_feedback_handoff",
    "build_feedback_confidence",
    "build_reviewer_queue",
    "generate_feedback_items",
    "load_review_bundle",
    "load_review_queue",
    "persist_feedback_annotation",
    "read_feedback_annotations",
    "read_feedback_items",
    "read_latest_adjudication",
    "read_reviewer_profile",
    "read_reviewer_profiles",
    "score_review_calibration",
    "score_reviewer_calibration",
    "submit_review_annotation",
    "write_adjudication_record",
    "write_calibration_result",
    "write_feedback_annotation",
    "write_feedback_item",
    "write_reviewer_profile",
]
